### ISSUE TITLE
www.hammerspoon.org/Spoons/ is now an empty page

### ISSUE THREAD

**Issue by russelldavis** [Hammerspoon/Spoons#206]
It is linked to at the top of https://www.hammerspoon.org/ and in the About section of this repo on github. It looks like [this commit](https://github.com/Hammerspoon/Spoons/commit/6fb865fe6f00c5be4dab6dc10094a16693dfe821#diff-b04b38d4e36f7a7171aeb211bf933eaf36d41d9866ebbc3639f673f84dc350ae) deleted the contents of docs/index.html for some reason.

**Comment by latenitefilms** [comment]
Paging @cmsj or @asmagill ?

**Comment by asmagill** [comment]
I've not worked on the Spoons repository before (and the one time I tried updating a spoon directly, I screwed up the archive for it), so I'd prefer to defer to @cmsj on this one...

That said, I know his time is limited at present, so I can try to take a look at it in a day or so and see what I can come up with... it looks like one of the automated process he's set up may be misconfigured because the referenced pull isn't associated with a user.

**Comment by cmsj** [comment]
Sorry, this was my fault, I've been fighting with GitHub Actions for our CI and somehow it broke the Spoons Actions. The Spoons page should be up again now. Thanks @russelldavis
