### ISSUE TITLE
Caffeine is showing multiple icons in the status bar

### ISSUE THREAD

**Issue by ahmedelgabri** [Hammerspoon/Spoons#63]
How can I cleanup this? Only one of them works but the others are still there.

<img width="80" alt="screen shot 2018-01-02 at 12 44 38" src="https://user-images.githubusercontent.com/63876/34482807-bd954fba-efba-11e7-8c0d-54c7c4e30966.png">

This is my config https://github.com/ahmedelgabri/dotfiles/blob/a47a08d5a59cfb9c83366939fb0870619208bd79/hammerspoon/.hammerspoon/spoons.lua

**Comment by leonardoshibata** [comment]
Second that. Every time I reload the config a new icon is created.

**Comment by asmagill** [comment]
The only way I can replicate this effect is if I start the Caffeine spoon multiple times *without* reloading Hammerspoon in between...

So:

1. What happens when you click on one of these extra icons?
2. Are you using any type of extension which manages/manipulates the menubar like Bartender?
3. How are you reloading Hammerspoon?

To address the specific case I *can* replicate, I've submitted an update at #65 which you can check out and see if it helps with your specific issue (if you're not familiar with git and merging pull requests, you can manually make the additions highlighted in green at https://github.com/Hammerspoon/Spoons/pull/65/files to your copy of `~/.hammerspoon/Spoons/Caffeine.spoon/init.lua` or wait until the request is accepted and merged into the repository master and then update your local copy with `spoon.SpoonInstall: installSpoonFromRepo('Caffeine')` -- as far as I can tell, the `andUse` method doesn't check for updates if a local copy already exists.)

**Comment by ahmedelgabri** [comment]
I tested the PR & it's working fine with me now, thanks @asmagill

**Comment by cmsj** [comment]
Thanks all. PR Merged!
